Neos:
  Neos:
    Ui:
      resources:
        javascript:
          Carbon.TailwindColors:
            resource: resource://Carbon.TailwindColors/Public/Plugin.js
        stylesheets:
          Carbon.TailwindColors:
            resource: resource://Carbon.TailwindColors/Public/stylex.css
    userInterface:
      translation:
        autoInclude:
          Carbon.TailwindColors:
            - Main
